### ISSUE TITLE
Will there be support for JSON/JSONB data types and searching?

### ISSUE THREAD

**Issue by andrew-sledge** [pjwerneck/flask-rql#2]
Vanilla RQLAlchemy doesn't seem to support this. Is this on the roadmap (and if so, what's the timeline), or can we get it on the roadmap? Thanks!

**Comment by pjwerneck** [comment]
That's an interesting idea, but it all depends on SQLAlchemy support. I'll look into it.

**Comment by andrew-sledge** [comment]
Was the SQLAlchemy support just not there?
