### ISSUE TITLE
Update rqlalchemy for SQLAlchemy 2.0 Compatibility

### ISSUE THREAD

**Issue by stout-yeoman** [pjwerneck/flask-rql#6]
I've initiated updates to make rqlalchemy compatible with SQLAlchemy 2.0, addressing API changes and dependency issues. It would be great to get feedback and collaboration on this.

SQLAlchemy 2.0 introduces new features and improvements but also breaks compatibility with rqlalchemy. This update will be useful for developers who are keen on leveraging SQLAlchemy 2.0’s advancements while using rqlalchemy. I've also made some additional changes that were required for making rqlalchemy work for our usecase.

I'm proposing the following changes:
- Align rqlalchemy with the updated APIs in SQLAlchemy 2.0
- Enable handling of JSON types
- Enable handling of aliased relationships
- Enable operating on multiple relationships
- Enable operating on self referential relationships

Looking forward to collaborating on this :)

**Comment by pjwerneck** [comment]
@stout-yeoman Absolutely, let's do it. Open a PR with whatever you have for the 2.0 update so I don't duplicate your work, and once we have 2.0 compatibility out we can work on those changes.

**Comment by pjwerneck** [comment]
@stout-yeoman I added a project and sent you an invite.
